[project]
name = "fmkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.7",
    "numpy>=1.24,<3",
    "pandas>=2.0",
    "scikit-learn>=1.3",
    "scipy>=1.11",
]
